/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Yodlee.ApiClient.Api;
using Yodlee.ApiClient.Model;
using Yodlee.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Yodlee.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ClassificationSummaryTransactionSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClassificationSummaryTransactionSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClassificationSummaryTransactionSummary
        //private ClassificationSummaryTransactionSummary instance;

        public ClassificationSummaryTransactionSummaryTests()
        {
            // TODO uncomment below to create an instance of ClassificationSummaryTransactionSummary
            //instance = new ClassificationSummaryTransactionSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClassificationSummaryTransactionSummary
        /// </summary>
        [Fact]
        public void ClassificationSummaryTransactionSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClassificationSummaryTransactionSummary
            //Assert.IsType<ClassificationSummaryTransactionSummary>(instance);
        }


        /// <summary>
        /// Test the property 'FromDate'
        /// </summary>
        [Fact]
        public void FromDateTest()
        {
            // TODO unit test for the property 'FromDate'
        }
        /// <summary>
        /// Test the property 'CardPayments'
        /// </summary>
        [Fact]
        public void CardPaymentsTest()
        {
            // TODO unit test for the property 'CardPayments'
        }
        /// <summary>
        /// Test the property 'IsPrimaryAccount'
        /// </summary>
        [Fact]
        public void IsPrimaryAccountTest()
        {
            // TODO unit test for the property 'IsPrimaryAccount'
        }
        /// <summary>
        /// Test the property 'LoanPayments'
        /// </summary>
        [Fact]
        public void LoanPaymentsTest()
        {
            // TODO unit test for the property 'LoanPayments'
        }
        /// <summary>
        /// Test the property 'ToDate'
        /// </summary>
        [Fact]
        public void ToDateTest()
        {
            // TODO unit test for the property 'ToDate'
        }
        /// <summary>
        /// Test the property 'BillPayments'
        /// </summary>
        [Fact]
        public void BillPaymentsTest()
        {
            // TODO unit test for the property 'BillPayments'
        }
        /// <summary>
        /// Test the property 'MortgagePayments'
        /// </summary>
        [Fact]
        public void MortgagePaymentsTest()
        {
            // TODO unit test for the property 'MortgagePayments'
        }
        /// <summary>
        /// Test the property 'SalaryCredits'
        /// </summary>
        [Fact]
        public void SalaryCreditsTest()
        {
            // TODO unit test for the property 'SalaryCredits'
        }
        /// <summary>
        /// Test the property 'IsActiveAccount'
        /// </summary>
        [Fact]
        public void IsActiveAccountTest()
        {
            // TODO unit test for the property 'IsActiveAccount'
        }
        /// <summary>
        /// Test the property 'LatestTransactions'
        /// </summary>
        [Fact]
        public void LatestTransactionsTest()
        {
            // TODO unit test for the property 'LatestTransactions'
        }
        /// <summary>
        /// Test the property 'IncomeCredits'
        /// </summary>
        [Fact]
        public void IncomeCreditsTest()
        {
            // TODO unit test for the property 'IncomeCredits'
        }

    }

}
