/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Yodlee.ApiClient.Api;
using Yodlee.ApiClient.Model;
using Yodlee.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Yodlee.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing Consent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Consent
        //private Consent instance;

        public ConsentTests()
        {
            // TODO uncomment below to create an instance of Consent
            //instance = new Consent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Consent
        /// </summary>
        [Fact]
        public void ConsentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Consent
            //Assert.IsType<Consent>(instance);
        }


        /// <summary>
        /// Test the property 'DataAccessFrequency'
        /// </summary>
        [Fact]
        public void DataAccessFrequencyTest()
        {
            // TODO unit test for the property 'DataAccessFrequency'
        }
        /// <summary>
        /// Test the property 'ExpirationDateTime'
        /// </summary>
        [Fact]
        public void ExpirationDateTimeTest()
        {
            // TODO unit test for the property 'ExpirationDateTime'
        }
        /// <summary>
        /// Test the property 'OtspADR'
        /// </summary>
        [Fact]
        public void OtspADRTest()
        {
            // TODO unit test for the property 'OtspADR'
        }
        /// <summary>
        /// Test the property 'ClientTrustedAdvisor'
        /// </summary>
        [Fact]
        public void ClientTrustedAdvisorTest()
        {
            // TODO unit test for the property 'ClientTrustedAdvisor'
        }
        /// <summary>
        /// Test the property 'ProviderConsentId'
        /// </summary>
        [Fact]
        public void ProviderConsentIdTest()
        {
            // TODO unit test for the property 'ProviderConsentId'
        }
        /// <summary>
        /// Test the property 'RevokeDate'
        /// </summary>
        [Fact]
        public void RevokeDateTest()
        {
            // TODO unit test for the property 'RevokeDate'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'ApplicationDisplayName'
        /// </summary>
        [Fact]
        public void ApplicationDisplayNameTest()
        {
            // TODO unit test for the property 'ApplicationDisplayName'
        }
        /// <summary>
        /// Test the property 'ConsentId'
        /// </summary>
        [Fact]
        public void ConsentIdTest()
        {
            // TODO unit test for the property 'ConsentId'
        }
        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Fact]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }
        /// <summary>
        /// Test the property 'ConsentStatus'
        /// </summary>
        [Fact]
        public void ConsentStatusTest()
        {
            // TODO unit test for the property 'ConsentStatus'
        }
        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }
        /// <summary>
        /// Test the property 'UserDataTreatment'
        /// </summary>
        [Fact]
        public void UserDataTreatmentTest()
        {
            // TODO unit test for the property 'UserDataTreatment'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Fact]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
        /// <summary>
        /// Test the property 'OtspADRName'
        /// </summary>
        [Fact]
        public void OtspADRNameTest()
        {
            // TODO unit test for the property 'OtspADRName'
        }
        /// <summary>
        /// Test the property 'Preferences'
        /// </summary>
        [Fact]
        public void PreferencesTest()
        {
            // TODO unit test for the property 'Preferences'
        }
        /// <summary>
        /// Test the property 'ClientADR'
        /// </summary>
        [Fact]
        public void ClientADRTest()
        {
            // TODO unit test for the property 'ClientADR'
        }
        /// <summary>
        /// Test the property 'Renewal'
        /// </summary>
        [Fact]
        public void RenewalTest()
        {
            // TODO unit test for the property 'Renewal'
        }
        /// <summary>
        /// Test the property 'RevokeDateTime'
        /// </summary>
        [Fact]
        public void RevokeDateTimeTest()
        {
            // TODO unit test for the property 'RevokeDateTime'
        }
        /// <summary>
        /// Test the property 'TitleBody'
        /// </summary>
        [Fact]
        public void TitleBodyTest()
        {
            // TODO unit test for the property 'TitleBody'
        }
        /// <summary>
        /// Test the property 'StartDateTime'
        /// </summary>
        [Fact]
        public void StartDateTimeTest()
        {
            // TODO unit test for the property 'StartDateTime'
        }
        /// <summary>
        /// Test the property 'ThirdPartyADR'
        /// </summary>
        [Fact]
        public void ThirdPartyADRTest()
        {
            // TODO unit test for the property 'ThirdPartyADR'
        }
        /// <summary>
        /// Test the property 'ProviderAccountId'
        /// </summary>
        [Fact]
        public void ProviderAccountIdTest()
        {
            // TODO unit test for the property 'ProviderAccountId'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

    }

}
