/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Yodlee.ApiClient.Api;
using Yodlee.ApiClient.Model;
using Yodlee.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Yodlee.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing DataExtractsTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataExtractsTransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataExtractsTransaction
        //private DataExtractsTransaction instance;

        public DataExtractsTransactionTests()
        {
            // TODO uncomment below to create an instance of DataExtractsTransaction
            //instance = new DataExtractsTransaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataExtractsTransaction
        /// </summary>
        [Fact]
        public void DataExtractsTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataExtractsTransaction
            //Assert.IsType<DataExtractsTransaction>(instance);
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Fact]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'CusipNumber'
        /// </summary>
        [Fact]
        public void CusipNumberTest()
        {
            // TODO unit test for the property 'CusipNumber'
        }
        /// <summary>
        /// Test the property 'HighLevelCategoryId'
        /// </summary>
        [Fact]
        public void HighLevelCategoryIdTest()
        {
            // TODO unit test for the property 'HighLevelCategoryId'
        }
        /// <summary>
        /// Test the property 'DetailCategoryId'
        /// </summary>
        [Fact]
        public void DetailCategoryIdTest()
        {
            // TODO unit test for the property 'DetailCategoryId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Fact]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'SettleDate'
        /// </summary>
        [Fact]
        public void SettleDateTest()
        {
            // TODO unit test for the property 'SettleDate'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Intermediary'
        /// </summary>
        [Fact]
        public void IntermediaryTest()
        {
            // TODO unit test for the property 'Intermediary'
        }
        /// <summary>
        /// Test the property 'BaseType'
        /// </summary>
        [Fact]
        public void BaseTypeTest()
        {
            // TODO unit test for the property 'BaseType'
        }
        /// <summary>
        /// Test the property 'CategorySource'
        /// </summary>
        [Fact]
        public void CategorySourceTest()
        {
            // TODO unit test for the property 'CategorySource'
        }
        /// <summary>
        /// Test the property 'Principal'
        /// </summary>
        [Fact]
        public void PrincipalTest()
        {
            // TODO unit test for the property 'Principal'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Fact]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }
        /// <summary>
        /// Test the property 'Interest'
        /// </summary>
        [Fact]
        public void InterestTest()
        {
            // TODO unit test for the property 'Interest'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Commission'
        /// </summary>
        [Fact]
        public void CommissionTest()
        {
            // TODO unit test for the property 'Commission'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'MerchantType'
        /// </summary>
        [Fact]
        public void MerchantTypeTest()
        {
            // TODO unit test for the property 'MerchantType'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'CheckNumber'
        /// </summary>
        [Fact]
        public void CheckNumberTest()
        {
            // TODO unit test for the property 'CheckNumber'
        }
        /// <summary>
        /// Test the property 'IsPhysical'
        /// </summary>
        [Fact]
        public void IsPhysicalTest()
        {
            // TODO unit test for the property 'IsPhysical'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Valoren'
        /// </summary>
        [Fact]
        public void ValorenTest()
        {
            // TODO unit test for the property 'Valoren'
        }
        /// <summary>
        /// Test the property 'IsManual'
        /// </summary>
        [Fact]
        public void IsManualTest()
        {
            // TODO unit test for the property 'IsManual'
        }
        /// <summary>
        /// Test the property 'Merchant'
        /// </summary>
        [Fact]
        public void MerchantTest()
        {
            // TODO unit test for the property 'Merchant'
        }
        /// <summary>
        /// Test the property 'Sedol'
        /// </summary>
        [Fact]
        public void SedolTest()
        {
            // TODO unit test for the property 'Sedol'
        }
        /// <summary>
        /// Test the property 'TransactionDate'
        /// </summary>
        [Fact]
        public void TransactionDateTest()
        {
            // TODO unit test for the property 'TransactionDate'
        }
        /// <summary>
        /// Test the property 'CategoryType'
        /// </summary>
        [Fact]
        public void CategoryTypeTest()
        {
            // TODO unit test for the property 'CategoryType'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'SourceType'
        /// </summary>
        [Fact]
        public void SourceTypeTest()
        {
            // TODO unit test for the property 'SourceType'
        }
        /// <summary>
        /// Test the property 'CONTAINER'
        /// </summary>
        [Fact]
        public void CONTAINERTest()
        {
            // TODO unit test for the property 'CONTAINER'
        }
        /// <summary>
        /// Test the property 'PostDate'
        /// </summary>
        [Fact]
        public void PostDateTest()
        {
            // TODO unit test for the property 'PostDate'
        }
        /// <summary>
        /// Test the property 'ParentCategoryId'
        /// </summary>
        [Fact]
        public void ParentCategoryIdTest()
        {
            // TODO unit test for the property 'ParentCategoryId'
        }
        /// <summary>
        /// Test the property 'SubType'
        /// </summary>
        [Fact]
        public void SubTypeTest()
        {
            // TODO unit test for the property 'SubType'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'RunningBalance'
        /// </summary>
        [Fact]
        public void RunningBalanceTest()
        {
            // TODO unit test for the property 'RunningBalance'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Fact]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'HoldingDescription'
        /// </summary>
        [Fact]
        public void HoldingDescriptionTest()
        {
            // TODO unit test for the property 'HoldingDescription'
        }
        /// <summary>
        /// Test the property 'Isin'
        /// </summary>
        [Fact]
        public void IsinTest()
        {
            // TODO unit test for the property 'Isin'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
