/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Yodlee.ApiClient.Api;
using Yodlee.ApiClient.Model;
using Yodlee.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Yodlee.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing DerivedTransactionsSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DerivedTransactionsSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DerivedTransactionsSummary
        //private DerivedTransactionsSummary instance;

        public DerivedTransactionsSummaryTests()
        {
            // TODO uncomment below to create an instance of DerivedTransactionsSummary
            //instance = new DerivedTransactionsSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DerivedTransactionsSummary
        /// </summary>
        [Fact]
        public void DerivedTransactionsSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DerivedTransactionsSummary
            //Assert.IsType<DerivedTransactionsSummary>(instance);
        }


        /// <summary>
        /// Test the property 'CategoryType'
        /// </summary>
        [Fact]
        public void CategoryTypeTest()
        {
            // TODO unit test for the property 'CategoryType'
        }
        /// <summary>
        /// Test the property 'CategorySummary'
        /// </summary>
        [Fact]
        public void CategorySummaryTest()
        {
            // TODO unit test for the property 'CategorySummary'
        }
        /// <summary>
        /// Test the property 'CreditTotal'
        /// </summary>
        [Fact]
        public void CreditTotalTest()
        {
            // TODO unit test for the property 'CreditTotal'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'DebitTotal'
        /// </summary>
        [Fact]
        public void DebitTotalTest()
        {
            // TODO unit test for the property 'DebitTotal'
        }

    }

}
