/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Yodlee.ApiClient.Api;
using Yodlee.ApiClient.Model;
using Yodlee.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Yodlee.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentAccountBalance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentAccountBalanceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentAccountBalance
        //private PaymentAccountBalance instance;

        public PaymentAccountBalanceTests()
        {
            // TODO uncomment below to create an instance of PaymentAccountBalance
            //instance = new PaymentAccountBalance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentAccountBalance
        /// </summary>
        [Fact]
        public void PaymentAccountBalanceInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentAccountBalance
            //Assert.IsType<PaymentAccountBalance>(instance);
        }


        /// <summary>
        /// Test the property 'AccountStatus'
        /// </summary>
        [Fact]
        public void AccountStatusTest()
        {
            // TODO unit test for the property 'AccountStatus'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Fact]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Fact]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'CurrentBalance'
        /// </summary>
        [Fact]
        public void CurrentBalanceTest()
        {
            // TODO unit test for the property 'CurrentBalance'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AvailableBalance'
        /// </summary>
        [Fact]
        public void AvailableBalanceTest()
        {
            // TODO unit test for the property 'AvailableBalance'
        }

    }

}
