/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yodlee.ApiClient.Client.OpenAPIDateConverter;

namespace Yodlee.ApiClient.Model
{
    /// <summary>
    /// AccountProfileDetail
    /// </summary>
    [DataContract(Name = "AccountProfileDetail")]
    public partial class AccountProfileDetail : IEquatable<AccountProfileDetail>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountProfileDetail" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public AccountProfileDetail()
        {
        }

        /// <summary>
        /// Identifiers available in the profile page of the account.&lt;br&gt;&lt;b&gt;Endpoints&lt;/b&gt;:&lt;li&gt;GET /partner/paymentProcessor/account/holder&lt;/li&gt;&lt;/ul&gt;
        /// </summary>
        /// <value>Identifiers available in the profile page of the account.&lt;br&gt;&lt;b&gt;Endpoints&lt;/b&gt;:&lt;li&gt;GET /partner/paymentProcessor/account/holder&lt;/li&gt;&lt;/ul&gt;</value>
        [DataMember(Name = "identifier", EmitDefaultValue = false)]
        public List<Identifier> Identifier { get; private set; }

        /// <summary>
        /// Returns false as Identifier should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeIdentifier()
        {
            return false;
        }
        /// <summary>
        /// Address available in the profile page of the account.&lt;br&gt;&lt;b&gt;Endpoints&lt;/b&gt;:&lt;li&gt;GET /partner/paymentProcessor/account/holder&lt;/li&gt;&lt;/ul&gt;
        /// </summary>
        /// <value>Address available in the profile page of the account.&lt;br&gt;&lt;b&gt;Endpoints&lt;/b&gt;:&lt;li&gt;GET /partner/paymentProcessor/account/holder&lt;/li&gt;&lt;/ul&gt;</value>
        [DataMember(Name = "address", EmitDefaultValue = false)]
        public List<AccountAddress> Address { get; private set; }

        /// <summary>
        /// Returns false as Address should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAddress()
        {
            return false;
        }
        /// <summary>
        /// Phone number available in the profile page of the account.&lt;br&gt;&lt;b&gt;Endpoints&lt;/b&gt;:&lt;li&gt;GET /partner/paymentProcessor/account/holder&lt;/li&gt;&lt;/ul&gt;
        /// </summary>
        /// <value>Phone number available in the profile page of the account.&lt;br&gt;&lt;b&gt;Endpoints&lt;/b&gt;:&lt;li&gt;GET /partner/paymentProcessor/account/holder&lt;/li&gt;&lt;/ul&gt;</value>
        [DataMember(Name = "phoneNumber", EmitDefaultValue = false)]
        public List<PhoneNumber> PhoneNumber { get; private set; }

        /// <summary>
        /// Returns false as PhoneNumber should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePhoneNumber()
        {
            return false;
        }
        /// <summary>
        /// Email Id available in the profile page of the account.&lt;br&gt;&lt;b&gt;Endpoints&lt;/b&gt;:&lt;li&gt;GET /partner/paymentProcessor/account/holder&lt;/li&gt;&lt;/ul&gt;
        /// </summary>
        /// <value>Email Id available in the profile page of the account.&lt;br&gt;&lt;b&gt;Endpoints&lt;/b&gt;:&lt;li&gt;GET /partner/paymentProcessor/account/holder&lt;/li&gt;&lt;/ul&gt;</value>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public List<Email> Email { get; private set; }

        /// <summary>
        /// Returns false as Email should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeEmail()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountProfileDetail {\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AccountProfileDetail);
        }

        /// <summary>
        /// Returns true if AccountProfileDetail instances are equal
        /// </summary>
        /// <param name="input">Instance of AccountProfileDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccountProfileDetail input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Identifier == input.Identifier ||
                    this.Identifier != null &&
                    input.Identifier != null &&
                    this.Identifier.SequenceEqual(input.Identifier)
                ) && 
                (
                    this.Address == input.Address ||
                    this.Address != null &&
                    input.Address != null &&
                    this.Address.SequenceEqual(input.Address)
                ) && 
                (
                    this.PhoneNumber == input.PhoneNumber ||
                    this.PhoneNumber != null &&
                    input.PhoneNumber != null &&
                    this.PhoneNumber.SequenceEqual(input.PhoneNumber)
                ) && 
                (
                    this.Email == input.Email ||
                    this.Email != null &&
                    input.Email != null &&
                    this.Email.SequenceEqual(input.Email)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Identifier != null)
                {
                    hashCode = (hashCode * 59) + this.Identifier.GetHashCode();
                }
                if (this.Address != null)
                {
                    hashCode = (hashCode * 59) + this.Address.GetHashCode();
                }
                if (this.PhoneNumber != null)
                {
                    hashCode = (hashCode * 59) + this.PhoneNumber.GetHashCode();
                }
                if (this.Email != null)
                {
                    hashCode = (hashCode * 59) + this.Email.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
