/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yodlee.ApiClient.Client.OpenAPIDateConverter;

namespace Yodlee.ApiClient.Model
{
    /// <summary>
    /// PaymentProcessorTokenRequest
    /// </summary>
    [DataContract(Name = "PaymentProcessorTokenRequest")]
    public partial class PaymentProcessorTokenRequest : IEquatable<PaymentProcessorTokenRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentProcessorTokenRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentProcessorTokenRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentProcessorTokenRequest" /> class.
        /// </summary>
        /// <param name="accountId">The unique identifier for the user&#39;s account. (required).</param>
        /// <param name="processor">The payment processor with whom the customer is integrating. (required).</param>
        public PaymentProcessorTokenRequest(List<long> accountId = default(List<long>), string processor = default(string))
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for PaymentProcessorTokenRequest and cannot be null");
            }
            this.AccountId = accountId;
            // to ensure "processor" is required (not null)
            if (processor == null)
            {
                throw new ArgumentNullException("processor is a required property for PaymentProcessorTokenRequest and cannot be null");
            }
            this.Processor = processor;
        }

        /// <summary>
        /// The unique identifier for the user&#39;s account.
        /// </summary>
        /// <value>The unique identifier for the user&#39;s account.</value>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public List<long> AccountId { get; set; }

        /// <summary>
        /// The payment processor with whom the customer is integrating.
        /// </summary>
        /// <value>The payment processor with whom the customer is integrating.</value>
        [DataMember(Name = "processor", IsRequired = true, EmitDefaultValue = true)]
        public string Processor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentProcessorTokenRequest {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  Processor: ").Append(Processor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentProcessorTokenRequest);
        }

        /// <summary>
        /// Returns true if PaymentProcessorTokenRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentProcessorTokenRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentProcessorTokenRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AccountId == input.AccountId ||
                    this.AccountId != null &&
                    input.AccountId != null &&
                    this.AccountId.SequenceEqual(input.AccountId)
                ) && 
                (
                    this.Processor == input.Processor ||
                    (this.Processor != null &&
                    this.Processor.Equals(input.Processor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccountId != null)
                {
                    hashCode = (hashCode * 59) + this.AccountId.GetHashCode();
                }
                if (this.Processor != null)
                {
                    hashCode = (hashCode * 59) + this.Processor.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
