/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yodlee.ApiClient.Client.OpenAPIDateConverter;

namespace Yodlee.ApiClient.Model
{
    /// <summary>
    /// TransactionCategorizationRule
    /// </summary>
    [DataContract(Name = "TransactionCategorizationRule")]
    public partial class TransactionCategorizationRule : IEquatable<TransactionCategorizationRule>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionCategorizationRule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public TransactionCategorizationRule()
        {
        }

        /// <summary>
        /// Details of rules. &lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;
        /// </summary>
        /// <value>Details of rules. &lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;</value>
        [DataMember(Name = "ruleClauses", EmitDefaultValue = false)]
        public List<RuleClause> RuleClauses { get; private set; }

        /// <summary>
        /// Returns false as RuleClauses should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRuleClauses()
        {
            return false;
        }
        /// <summary>
        /// Unique identifier generated for every rule the user creates.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;
        /// </summary>
        /// <value>Unique identifier generated for every rule the user creates.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;</value>
        [DataMember(Name = "userDefinedRuleId", EmitDefaultValue = false)]
        public long UserDefinedRuleId { get; private set; }

        /// <summary>
        /// Returns false as UserDefinedRuleId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUserDefinedRuleId()
        {
            return false;
        }
        /// <summary>
        /// The level of the category for which the rule is created.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, insurance, loan&lt;br&gt;
        /// </summary>
        /// <value>The level of the category for which the rule is created.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, insurance, loan&lt;br&gt;</value>
        [DataMember(Name = "categoryLevelId", EmitDefaultValue = false)]
        public int CategoryLevelId { get; private set; }

        /// <summary>
        /// Returns false as CategoryLevelId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCategoryLevelId()
        {
            return false;
        }
        /// <summary>
        /// Category id that is assigned to the transaction when the transaction matches the rule clause. This is the id field of the transaction category resource.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;
        /// </summary>
        /// <value>Category id that is assigned to the transaction when the transaction matches the rule clause. This is the id field of the transaction category resource.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;</value>
        [DataMember(Name = "transactionCategorisationId", EmitDefaultValue = false)]
        public long TransactionCategorisationId { get; private set; }

        /// <summary>
        /// Returns false as TransactionCategorisationId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTransactionCategorisationId()
        {
            return false;
        }
        /// <summary>
        /// Unique identifier of the user.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;
        /// </summary>
        /// <value>Unique identifier of the user.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;</value>
        [DataMember(Name = "memId", EmitDefaultValue = false)]
        public long MemId { get; private set; }

        /// <summary>
        /// Returns false as MemId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMemId()
        {
            return false;
        }
        /// <summary>
        /// The order in which the rules get executed on transactions.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;
        /// </summary>
        /// <value>The order in which the rules get executed on transactions.&lt;br&gt;&lt;br&gt;&lt;b&gt;Applicable containers&lt;/b&gt;: creditCard, investment, insurance, loan&lt;br&gt;</value>
        [DataMember(Name = "rulePriority", EmitDefaultValue = false)]
        public int RulePriority { get; private set; }

        /// <summary>
        /// Returns false as RulePriority should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRulePriority()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionCategorizationRule {\n");
            sb.Append("  RuleClauses: ").Append(RuleClauses).Append("\n");
            sb.Append("  UserDefinedRuleId: ").Append(UserDefinedRuleId).Append("\n");
            sb.Append("  CategoryLevelId: ").Append(CategoryLevelId).Append("\n");
            sb.Append("  TransactionCategorisationId: ").Append(TransactionCategorisationId).Append("\n");
            sb.Append("  MemId: ").Append(MemId).Append("\n");
            sb.Append("  RulePriority: ").Append(RulePriority).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionCategorizationRule);
        }

        /// <summary>
        /// Returns true if TransactionCategorizationRule instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionCategorizationRule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionCategorizationRule input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RuleClauses == input.RuleClauses ||
                    this.RuleClauses != null &&
                    input.RuleClauses != null &&
                    this.RuleClauses.SequenceEqual(input.RuleClauses)
                ) && 
                (
                    this.UserDefinedRuleId == input.UserDefinedRuleId ||
                    this.UserDefinedRuleId.Equals(input.UserDefinedRuleId)
                ) && 
                (
                    this.CategoryLevelId == input.CategoryLevelId ||
                    this.CategoryLevelId.Equals(input.CategoryLevelId)
                ) && 
                (
                    this.TransactionCategorisationId == input.TransactionCategorisationId ||
                    this.TransactionCategorisationId.Equals(input.TransactionCategorisationId)
                ) && 
                (
                    this.MemId == input.MemId ||
                    this.MemId.Equals(input.MemId)
                ) && 
                (
                    this.RulePriority == input.RulePriority ||
                    this.RulePriority.Equals(input.RulePriority)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RuleClauses != null)
                {
                    hashCode = (hashCode * 59) + this.RuleClauses.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.UserDefinedRuleId.GetHashCode();
                hashCode = (hashCode * 59) + this.CategoryLevelId.GetHashCode();
                hashCode = (hashCode * 59) + this.TransactionCategorisationId.GetHashCode();
                hashCode = (hashCode * 59) + this.MemId.GetHashCode();
                hashCode = (hashCode * 59) + this.RulePriority.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
