/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yodlee.ApiClient.Client.OpenAPIDateConverter;

namespace Yodlee.ApiClient.Model
{
    /// <summary>
    /// TransactionCategorizationRuleInfo
    /// </summary>
    [DataContract(Name = "TransactionCategorizationRuleInfo")]
    public partial class TransactionCategorizationRuleInfo : IEquatable<TransactionCategorizationRuleInfo>, IValidatableObject
    {
        /// <summary>
        /// Defines Source
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SourceEnum
        {
            /// <summary>
            /// Enum SYSTEM for value: SYSTEM
            /// </summary>
            [EnumMember(Value = "SYSTEM")]
            SYSTEM = 1,

            /// <summary>
            /// Enum USER for value: USER
            /// </summary>
            [EnumMember(Value = "USER")]
            USER = 2

        }


        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name = "source", EmitDefaultValue = false)]
        public SourceEnum? Source { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionCategorizationRuleInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionCategorizationRuleInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionCategorizationRuleInfo" /> class.
        /// </summary>
        /// <param name="ruleClause">ruleClause (required).</param>
        /// <param name="source">source.</param>
        /// <param name="priority">priority.</param>
        /// <param name="categoryId">categoryId (required).</param>
        public TransactionCategorizationRuleInfo(List<FieldOperation> ruleClause = default(List<FieldOperation>), SourceEnum? source = default(SourceEnum?), int priority = default(int), int categoryId = default(int))
        {
            // to ensure "ruleClause" is required (not null)
            if (ruleClause == null)
            {
                throw new ArgumentNullException("ruleClause is a required property for TransactionCategorizationRuleInfo and cannot be null");
            }
            this.RuleClause = ruleClause;
            this.CategoryId = categoryId;
            this.Source = source;
            this.Priority = priority;
        }

        /// <summary>
        /// Gets or Sets RuleClause
        /// </summary>
        [DataMember(Name = "ruleClause", IsRequired = true, EmitDefaultValue = true)]
        public List<FieldOperation> RuleClause { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public int Priority { get; set; }

        /// <summary>
        /// Gets or Sets CategoryId
        /// </summary>
        [DataMember(Name = "categoryId", IsRequired = true, EmitDefaultValue = true)]
        public int CategoryId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionCategorizationRuleInfo {\n");
            sb.Append("  RuleClause: ").Append(RuleClause).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionCategorizationRuleInfo);
        }

        /// <summary>
        /// Returns true if TransactionCategorizationRuleInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionCategorizationRuleInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionCategorizationRuleInfo input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RuleClause == input.RuleClause ||
                    this.RuleClause != null &&
                    input.RuleClause != null &&
                    this.RuleClause.SequenceEqual(input.RuleClause)
                ) && 
                (
                    this.Source == input.Source ||
                    this.Source.Equals(input.Source)
                ) && 
                (
                    this.Priority == input.Priority ||
                    this.Priority.Equals(input.Priority)
                ) && 
                (
                    this.CategoryId == input.CategoryId ||
                    this.CategoryId.Equals(input.CategoryId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RuleClause != null)
                {
                    hashCode = (hashCode * 59) + this.RuleClause.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Source.GetHashCode();
                hashCode = (hashCode * 59) + this.Priority.GetHashCode();
                hashCode = (hashCode * 59) + this.CategoryId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
