/*
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Yodlee.ApiClient.Client.OpenAPIDateConverter;

namespace Yodlee.ApiClient.Model
{
    /// <summary>
    /// VerifyAccount
    /// </summary>
    [DataContract(Name = "VerifyAccount")]
    public partial class VerifyAccount : IEquatable<VerifyAccount>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyAccount" /> class.
        /// </summary>
        /// <param name="transactionCriteria">transactionCriteria.</param>
        /// <param name="account">account.</param>
        public VerifyAccount(List<VerifyTransactionCriteria> transactionCriteria = default(List<VerifyTransactionCriteria>), List<VerifiedAccount> account = default(List<VerifiedAccount>))
        {
            this.TransactionCriteria = transactionCriteria;
            this.Account = account;
        }

        /// <summary>
        /// Gets or Sets TransactionCriteria
        /// </summary>
        [DataMember(Name = "transactionCriteria", EmitDefaultValue = false)]
        public List<VerifyTransactionCriteria> TransactionCriteria { get; set; }

        /// <summary>
        /// Gets or Sets Account
        /// </summary>
        [DataMember(Name = "account", EmitDefaultValue = false)]
        public List<VerifiedAccount> Account { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerifyAccount {\n");
            sb.Append("  TransactionCriteria: ").Append(TransactionCriteria).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VerifyAccount);
        }

        /// <summary>
        /// Returns true if VerifyAccount instances are equal
        /// </summary>
        /// <param name="input">Instance of VerifyAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VerifyAccount input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TransactionCriteria == input.TransactionCriteria ||
                    this.TransactionCriteria != null &&
                    input.TransactionCriteria != null &&
                    this.TransactionCriteria.SequenceEqual(input.TransactionCriteria)
                ) && 
                (
                    this.Account == input.Account ||
                    this.Account != null &&
                    input.Account != null &&
                    this.Account.SequenceEqual(input.Account)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransactionCriteria != null)
                {
                    hashCode = (hashCode * 59) + this.TransactionCriteria.GetHashCode();
                }
                if (this.Account != null)
                {
                    hashCode = (hashCode * 59) + this.Account.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
